arb-dir: lib/src/common/l10n
template-arb-file: app_en.arb
supported-locales: [en, zh, zh_TW]
output-localization-file: app_localizations.g.dart
output-class: AppLocalizations
use-deferred-loading: false