targets:
  $default:
    builders:
      hive_generator|hive_generator:
        enabled: true
        options:
          nullable_support: true

      source_gen|combining_builder:
        enabled: true
        options:
          ignore_for_file:
            - 'dart:async'
            - 'dart:convert'
            - 'dart:core'
            - 'dart:io'
            - 'dart:isolate'
            - 'dart:math'
            - 'dart:typed_data'
            - 'dart:ui'
            - 'package:flutter/material.dart'
            - 'package:flutter/widgets.dart'
            - 'package:hive/hive.dart'